# Generated by Django 5.1.2 on 2024-10-30 09:44

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PengajuanSurat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('SKP', 'Surat Keterangan Pindah'), ('SKN', 'Surat Keterangan Menikah'), ('SKTM', 'Surat Keterangan Tidak Mampu'), ('SKU', 'Surat Keterangan Usaha'), ('SKM', 'Surat Keterangan Meninggal')], max_length=255)),
                ('keterangan', models.TextField()),
                ('telefon', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='ID')),
                ('fotokopi_kartu_keluarga', models.FileField(upload_to='kartu_keluarga/')),
                ('surat_pengantar_rt_rw', models.FileField(upload_to='surat_pengantar/')),
            ],
            options={
                'verbose_name_plural': 'Pengajuan Surat',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Sedang Diproses', 'Sedang diproses'), ('Selesai Diproses', 'Selesai diproses')], max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Pengaduan',
            },
        ),
    ]
