# Generated by Django 5.1.2 on 2024-11-07 03:33

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Sedang Diproses', 'Sedang diproses'), ('Selesai Diproses', 'Selesai diproses')], max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pengaduan',
                'verbose_name_plural': 'Pengaduan Warga',
            },
        ),
        migrations.CreateModel(
            name='SuratKematian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.TextField()),
                ('telefon', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='ID')),
                ('fotokopi_kartu_keluarga', models.FileField(upload_to='kartu_keluarga/')),
                ('surat_pengantar_rt_rw', models.FileField(upload_to='surat_pengantar/')),
                ('surat_rumahsakit', models.FileField(blank=True, null=True, upload_to='surat_rumahsakit/')),
            ],
            options={
                'verbose_name_plural': 'Surat Kematian',
            },
        ),
        migrations.CreateModel(
            name='SuratNikah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.TextField()),
                ('telefon', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='ID')),
                ('fotokopi_kartu_keluarga', models.FileField(upload_to='kartu_keluarga/')),
                ('surat_pengantar_rt_rw', models.FileField(upload_to='surat_pengantar/')),
            ],
            options={
                'verbose_name_plural': 'Surat Nikah',
            },
        ),
        migrations.CreateModel(
            name='SuratPindah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.TextField()),
                ('telefon', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='ID')),
                ('fotokopi_kartu_keluarga', models.FileField(upload_to='kartu_keluarga/')),
                ('surat_pengantar_rt_rw', models.FileField(upload_to='surat_pengantar/')),
            ],
            options={
                'verbose_name_plural': 'Surat Pindah',
            },
        ),
        migrations.CreateModel(
            name='SuratTidakMampu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.TextField()),
                ('telefon', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='ID')),
                ('fotokopi_kartu_keluarga', models.FileField(upload_to='kartu_keluarga/')),
                ('surat_pengantar_rt_rw', models.FileField(upload_to='surat_pengantar/')),
            ],
            options={
                'verbose_name_plural': 'Surat Keterangan Tidak Mampu',
            },
        ),
        migrations.CreateModel(
            name='SuratUsaha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keterangan', models.TextField()),
                ('telefon', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='ID')),
                ('fotokopi_kartu_keluarga', models.FileField(upload_to='kartu_keluarga/')),
                ('surat_pengantar_rt_rw', models.FileField(upload_to='surat_pengantar/')),
            ],
            options={
                'verbose_name_plural': 'Surat Usaha',
            },
        ),
    ]
