# Generated by Django 5.1.2 on 2024-11-07 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superuser', '0002_alter_account_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 7, 13, 29, 2, 687886)),
        ),
    ]
