# Generated by Django 5.1.2 on 2024-11-07 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BLT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_penerima', models.CharField(max_length=500)),
                ('alamat', models.CharField(max_length=5000)),
                ('memenuhi_syarat', models.CharField(choices=[('Memenuhi Syarat', 'Memenuhi Syarat'), ('Tidak Memenuhi Syarat', 'Tidak Memenuhi Syarat')], max_length=255)),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Rupiah')),
            ],
        ),
        migrations.CreateModel(
            name='PKH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
