# Generated by Django 5.1.2 on 2024-11-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bantuan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blt',
            options={'verbose_name': 'BLT', 'verbose_name_plural': 'BLT'},
        ),
        migrations.AlterModelOptions(
            name='pkh',
            options={'verbose_name': 'PKH', 'verbose_name_plural': 'PKH'},
        ),
        migrations.AddField(
            model_name='pkh',
            name='alamat',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='pkh',
            name='nama',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pkh',
            name='rt',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True, verbose_name='RT'),
        ),
    ]
